# -*- coding: utf-8 -*-
"""cats and dogs app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TW-x00cA0gPYE2KINk3iZO14OmV1HNko
"""

import streamlit as st
import numpy as np
from PIL import Image
import tensorflow as tf
from tensorflow.keras.models import load_model

#config
IMG_HEIGHT = 150
IMG_WIDTH = 150
MODEL_PATH = "cats_dogs_cnn.h5"


@st.cache_resource
def load_cnn_model():
    model = load_model(MODEL_PATH)
    return model


def preprocess_image(img: Image.Image):
    img = img.resize((IMG_WIDTH, IMG_HEIGHT))
    img_array = np.array(img)

    if img_array.ndim == 2:
        img_array = np.stack([img_array]*3, axis=-1)
    elif img_array.shape[-1] == 4:
        img_array = img_array[..., :3]

    img_array = img_array / 255.0
    img_array = np.expand_dims(img_array, axis=0)
    return img_array


def predict_image(model, img_array):
    prob = model.predict(img_array)[0][0]
    label = "Dog 🐶" if prob > 0.5 else "Cat 🐱"
    confidence = prob if prob > 0.5 else 1 - prob
    return label, float(confidence)


def main():
    st.set_page_config(
        page_title="Cats vs Dogs Classifier",
        page_icon="🐱🐶",
        layout="centered"
    )

    st.title("Cats vs Dogs Classifier")
    st.write("Upload a photo of a **cat or dog**, and this model will try to guess which one it is.")

    model = load_cnn_model()

    uploaded_file = st.file_uploader(
        "Upload an image (JPG/PNG)",
        type=["jpg", "jpeg", "png"]
    )

    if uploaded_file is not None:
        image = Image.open(uploaded_file)
        st.image(image, caption="Uploaded image", use_column_width=True)

        if st.button("Predict"):
            with st.spinner("Analyzing image..."):
                img_array = preprocess_image(image)
                label, confidence = predict_image(model, img_array)

            st.subheader(f"Prediction: **{label}**")
            st.write(f"Confidence: **{confidence*100:.2f}%**")


if __name__ == "__main__":
    main()