# -*- coding: utf-8 -*-
"""cats and dogs app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TW-x00cA0gPYE2KINk3iZO14OmV1HNko
"""

from pathlib import Path

import numpy as np
import streamlit as st
import tensorflow as tf
from PIL import Image

#config
st.set_page_config(
    page_title="Cats vs Dogs Classifier",
    page_icon="🐾",
    layout="centered"
)

MODEL_PATH = Path(__file__).parent / "cats_dogs_cnn_small.h5"


@st.cache_resource
def load_cnn_model():
    if not MODEL_PATH.exists():
        st.error(f"Model file not found at: {MODEL_PATH}")
        raise FileNotFoundError(f"Model file not found at: {MODEL_PATH}")

    model = tf.keras.models.load_model(MODEL_PATH)
    return model


def preprocess_image(image: Image.Image, img_size=(150, 150)):
    image = image.convert("RGB")
    image = image.resize(img_size)
    img_array = tf.keras.preprocessing.image.img_to_array(image)
    img_array = img_array / 255.0
    img_array = np.expand_dims(img_array, axis=0)
    return img_array


def main():
    st.title("Cats vs Dogs Classifier")
    st.write(
        "Upload a photo of a **cat** or **dog**, and this model will try to guess which one it is. (abnormal photo or meme will be classified as **neither**)"
    )

    with st.sidebar:
        st.header("About the model")
        st.markdown(
            "- CNN trained on ~2000 images\n"
            "- Binary classification: **cat** vs **dog**\n"
            "- Built with TensorFlow + Streamlit"
        )

    try:
        model = load_cnn_model()
    except FileNotFoundError:
        st.stop()

    uploaded_file = st.file_uploader(
        "Choose an image...", type=["jpg", "jpeg", "png"]
    )

    if uploaded_file is not None:
        image = Image.open(uploaded_file)
        st.image(image, caption="Uploaded image", use_column_width=True)

        if st.button("Predict"):
    with st.spinner("Predicting..."):
        img_array = preprocess_image(image)
        pred = model.predict(img_array)[0][0]

        prob_dog = float(pred)
        prob_cat = float(1 - pred)

        threshold = 0.7

        if prob_dog >= threshold:
            label = "Dog 🐶"
            confidence = prob_dog
        elif prob_cat >= threshold:
            label = "Cat 🐱"
            confidence = prob_cat
        else:
            label = "Neither Cat nor Dog ❓"
            confidence = max(prob_dog, prob_cat)

        st.markdown(
            f"### Prediction: **{label}**\n"
            f"Confidence for Cat: **{prob_cat:.2%}**  \n"
            f"Confidence for Dog: **{prob_dog:.2%}**  \n"
            f"Final decision confidence: **{confidence:.2%}**"
        )




if __name__ == "__main__":
    main()